{% set name = "langcodes" %}
{% set version = "3.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langcodes-{{ version }}.tar.gz
  sha256: ae5a77d1a01d0d1e91854a671890892b7ce9abb601ab7327fc5c874f899e1979

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - langcodes
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/rspeer/langcodes
  summary: Labels and compares human languages in a standardized way
  license: MIT
  license_file: LICENSE.txt
  description: |
    Langcodes is a toolkit for working with and comparing the
     standardized codes for languages, such as 'en' for English, 'es'
     for Spanish, and 'zh-Hant' for Traditional Chinese. These are
     BCP 47 language codes, formerly known as ISO language codes.


extra:
  recipe-maintainers:
    - thewchan
