{% set name = "langcodes" %}
{% set version = "3.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langcodes-{{ version }}.tar.gz
  sha256: 1eef8168d07e51e131a2497ffecad4b663f6208e7c3ae3b8dc15c51734a6f801

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools >=60
    - setuptools-scm >=8.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - langcodes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/rspeer/langcodes
  summary: Labels and compares human languages in a standardized way
  license: MIT
  license_file: LICENSE.txt
  description: |
    Langcodes is a toolkit for working with and comparing the
     standardized codes for languages, such as 'en' for English, 'es'
     for Spanish, and 'zh-Hant' for Traditional Chinese. These are
     BCP 47 language codes, formerly known as ISO language codes.


extra:
  recipe-maintainers:
    - thewchan
