{% set name = "langcodes" %}
{% set version = "3.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langcodes-{{ version }}.tar.gz
  sha256: 40bff315e01b01d11c2ae3928dd4f5cbd74dd38f9bd912c12b9a3606c143f731

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools >=60
    - setuptools-scm >=8.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - language-data >=1.2

test:
  imports:
    - langcodes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/georgkrause/langcodes
  summary: Tools for labeling human languages with IETF language tags
  license: MIT
  license_file: LICENSE.txt
  description: |
    Langcodes is a toolkit for working with and comparing the
     standardized codes for languages, such as 'en' for English, 'es'
     for Spanish, and 'zh-Hant' for Traditional Chinese. These are
     BCP 47 language codes, formerly known as ISO language codes.


extra:
  recipe-maintainers:
    - thewchan
